version: '2'
services:
    issuetracker-app:
        image: issuetracker
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://issuetracker-postgresql:5432/IssueTracker
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://issuetracker-elasticsearch:9200
        ports:
            - 8080:8080
    issuetracker-postgresql:
        extends:
            file: postgresql.yml
            service: issuetracker-postgresql
    issuetracker-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: issuetracker-elasticsearch
